//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCAFE_WPF.View.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class QLCafeResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal QLCafeResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QLCAFE_WPF.View.Localization.QLCafeResources", typeof(QLCafeResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Name.
        /// </summary>
        public static string Account_DisplayName {
            get {
                return ResourceManager.GetString("Account_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id.
        /// </summary>
        public static string Account_id {
            get {
                return ResourceManager.GetString("Account_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Account_Password {
            get {
                return ResourceManager.GetString("Account_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Account_Type {
            get {
                return ResourceManager.GetString("Account_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string Account_UserName {
            get {
                return ResourceManager.GetString("Account_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts.
        /// </summary>
        public static string AccountPlural {
            get {
                return ResourceManager.GetString("AccountPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill.
        /// </summary>
        public static string Bill {
            get {
                return ResourceManager.GetString("Bill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Check In.
        /// </summary>
        public static string Bill_DateCheckIn {
            get {
                return ResourceManager.GetString("Bill_DateCheckIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Check Out.
        /// </summary>
        public static string Bill_DateCheckOut {
            get {
                return ResourceManager.GetString("Bill_DateCheckOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id.
        /// </summary>
        public static string Bill_id {
            get {
                return ResourceManager.GetString("Bill_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to status.
        /// </summary>
        public static string Bill_status {
            get {
                return ResourceManager.GetString("Bill_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tablefood.
        /// </summary>
        public static string Bill_Tablefood {
            get {
                return ResourceManager.GetString("Bill_Tablefood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill Info.
        /// </summary>
        public static string BillInfo {
            get {
                return ResourceManager.GetString("BillInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill.
        /// </summary>
        public static string BillInfo_Bill {
            get {
                return ResourceManager.GetString("BillInfo_Bill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to count1.
        /// </summary>
        public static string BillInfo_count1 {
            get {
                return ResourceManager.GetString("BillInfo_count1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food.
        /// </summary>
        public static string BillInfo_Food {
            get {
                return ResourceManager.GetString("BillInfo_Food", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id.
        /// </summary>
        public static string BillInfo_id {
            get {
                return ResourceManager.GetString("BillInfo_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill Infoes.
        /// </summary>
        public static string BillInfoPlural {
            get {
                return ResourceManager.GetString("BillInfoPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bills.
        /// </summary>
        public static string BillPlural {
            get {
                return ResourceManager.GetString("BillPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food.
        /// </summary>
        public static string Food {
            get {
                return ResourceManager.GetString("Food", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id.
        /// </summary>
        public static string Food_id {
            get {
                return ResourceManager.GetString("Food_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id Category.
        /// </summary>
        public static string Food_idCategory {
            get {
                return ResourceManager.GetString("Food_idCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name.
        /// </summary>
        public static string Food_name {
            get {
                return ResourceManager.GetString("Food_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to price.
        /// </summary>
        public static string Food_price {
            get {
                return ResourceManager.GetString("Food_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food Category.
        /// </summary>
        public static string FoodCategory {
            get {
                return ResourceManager.GetString("FoodCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id.
        /// </summary>
        public static string FoodCategory_id {
            get {
                return ResourceManager.GetString("FoodCategory_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name.
        /// </summary>
        public static string FoodCategory_name {
            get {
                return ResourceManager.GetString("FoodCategory_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food Categories.
        /// </summary>
        public static string FoodCategoryPlural {
            get {
                return ResourceManager.GetString("FoodCategoryPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foods.
        /// </summary>
        public static string FoodPlural {
            get {
                return ResourceManager.GetString("FoodPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tablefood.
        /// </summary>
        public static string Tablefood {
            get {
                return ResourceManager.GetString("Tablefood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id.
        /// </summary>
        public static string Tablefood_id {
            get {
                return ResourceManager.GetString("Tablefood_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name.
        /// </summary>
        public static string Tablefood_name {
            get {
                return ResourceManager.GetString("Tablefood_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to status.
        /// </summary>
        public static string Tablefood_status {
            get {
                return ResourceManager.GetString("Tablefood_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tablefoods.
        /// </summary>
        public static string TablefoodPlural {
            get {
                return ResourceManager.GetString("TablefoodPlural", resourceCulture);
            }
        }
    }
}
